### ISSUE TITLE
Should we consider symlinks?

### ISSUE THREAD

**Issue by Berrysoft** [Tim-Paik/FRFS#3]
https://github.com/Tim-Paik/FRFS/blob/a4efaa0b8941c922203bfc40f57be4d613bb5122/src/lib.rs#L183

Now we don't handle symlinks. It would be harmful when a symlink links to locations outside the packed folder.

**Comment by Tim-Paik** [comment]
We do not deal with symbolic links, this is only used to distinguish folders and files, these functions are implemented to directly replace std::fs without modification
I don't think there should be a symbolic link here, because this is not a real file system, and now it should copy the file corresponding to the symbolic link when constructing frfs. Are symbolic links any good?

See: https://github.com/Tim-Paik/FRFS/blob/a4efaa0b8941c922203bfc40f57be4d613bb5122/src/lib.rs#L246-L259

**Comment by Berrysoft** [comment]
Well, I don't think we need symlinks. And I don't think we need these symlink APIs :)
